"""empty message

Revision ID: 0aed293a7ff8
Revises: 94696a473aed
Create Date: 2018-08-19 16:06:24.239231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aed293a7ff8'
down_revision = '94696a473aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_collection', sa.Column('moviename', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_collection', 'moviename')
    # ### end Alembic commands ###
