"""empty message

Revision ID: 79281d95305d
Revises: 
Create Date: 2018-08-19 11:17:45.283747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79281d95305d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('url', sa.String(length=15), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('director', sa.Text(), nullable=True),
    sa.Column('actor', sa.Text(), nullable=True),
    sa.Column('genre', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('releasedate', sa.String(length=15), nullable=True),
    sa.Column('rating', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_table('user_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dateviewed', sa.String(length=15), nullable=True),
    sa.Column('movieurl', sa.String(length=15), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movieurl'], ['movie.url'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_collection')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_table('user')
    op.drop_table('movie')
    # ### end Alembic commands ###
